AllCops:
  DisplayCopNames: true

  Include:
    - '**/Rakefile'

  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false
